version: "3.9"
name: TodoList
services:
  web:
    build:
      context: ../..
      dockerfile: ./config/docker/Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - "../../src:/app/src"
    restart: always
