run-name: Dev workflow - Build and Test
name: CI/CD

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and test server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    environment: testing
    name: Run Postman tests
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Create env file
        run: |
            echo "${{ secrets.ENV_FILE }}" > .env
      - name: Run API tests
        run: |
          go run src/main.go & sleep 10 && postman collection run "${{ github.workspace }}/postman/collections/todoList.json" -e "15037258-1633bb9d-e860-457d-b2dc-57aa7d6aba65" --integration-id "139819-${{ github.run_id }}"
