run-name: Dev workflow - Test and deploy

on:
  push:
    branches:
      - feature/github-action

  pull_request:
    branches:
      - develop

jobs:
  build-test:
    name: Build and test server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Build
        run: go build -v ./...

  deploy:
    name: Deploy server
    needs: [build-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "this script will deploy the server 🚀"
